import type { Metadata } from 'next';
import { siteConfig } from '@/lib/site-config';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  alternates: { canonical: `${siteConfig.url}/legal/privacy` },
};

const sections = [
  {
    title: '1. Information we collect',
    body: 'We collect information you provide directly (name, email, phone, address, payment details) and information generated by your use of the platform (bookings, messages, reviews, device and usage data).',
  },
  {
    title: '2. How we use information',
    body: 'We use your information to operate the marketplace: matching you with providers, processing payments, sending booking and account notifications, preventing fraud, and improving the platform.',
  },
  {
    title: '3. Sharing information',
    body: 'We share the minimum necessary information between customers and providers to complete a booking (name, contact details, service address). We share data with payment processors, cloud infrastructure providers, and email/SMS providers strictly to operate the service.',
  },
  {
    title: '4. Payment information',
    body: 'Payment card details are processed and stored by Stripe, our PCI-compliant payment processor. FixLocal does not store full card numbers on its own servers.',
  },
  {
    title: '5. Cookies',
    body: 'We use cookies and similar technologies to keep you signed in, remember preferences, and understand how the platform is used. See our Cookie Policy for details.',
  },
  {
    title: '6. Data retention',
    body: 'We retain account and transaction data for as long as your account is active and as required to comply with legal, tax, and accounting obligations.',
  },
  {
    title: '7. Your rights',
    body: 'Depending on your location, you may have rights to access, correct, delete, or export your personal data. Contact us to exercise these rights.',
  },
  {
    title: '8. Security',
    body: 'We use industry-standard safeguards, including encryption in transit and at rest, and Row Level Security on our database, to protect your information.',
  },
  {
    title: '9. Children',
    body: 'FixLocal is not directed at individuals under 18, and we do not knowingly collect information from children.',
  },
  {
    title: '10. Contact',
    body: `Questions about this policy can be sent to ${siteConfig.supportEmail}.`,
  },
];

export default function PrivacyPage() {
  return (
    <div className="container max-w-3xl py-16">
      <h1 className="font-display text-4xl font-bold">Privacy Policy</h1>
      <p className="mt-2 text-sm text-muted-foreground">Last updated: January 1, 2026</p>

      <div className="mt-10 space-y-8">
        {sections.map((section) => (
          <div key={section.title}>
            <h2 className="font-display text-lg font-semibold">{section.title}</h2>
            <p className="mt-2 text-muted-foreground">{section.body}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
